/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package animating.algorithms;

import javax.swing.UIManager;

/**
 *
 * @author ash
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        menuPanel = new javax.swing.JPanel();
        lcsMenuButton = new javax.swing.JButton();
        knapsackMenuButton = new javax.swing.JButton();
        matrixMenuButton = new javax.swing.JButton();
        creditsLabel = new javax.swing.JLabel();
        menuLogo = new javax.swing.JLabel();
        menuTitle = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animating Algorithms");
        setBackground(new java.awt.Color(255, 255, 255));

        menuPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        lcsMenuButton.setFocusPainted(false);
        lcsMenuButton.setLabel("<html><center>Longest Common <br>Subsequence</center></html>");
        lcsMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcsMenuButtonActionPerformed(evt);
            }
        });

        knapsackMenuButton.setText("<html><center>Knapsack<br> (0,1)</center></html>");
        knapsackMenuButton.setFocusPainted(false);
        knapsackMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knapsackMenuButtonActionPerformed(evt);
            }
        });

        matrixMenuButton.setText("<html><center>Matrix Chain<br>Multiplication</center></html>");
        matrixMenuButton.setFocusPainted(false);
        matrixMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixMenuButtonActionPerformed(evt);
            }
        });

        creditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditsLabel.setText("<html><i>Created by Ashley Connor &copy; 2012 </i></html?>");

        menuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animating/algorithms/resources/University_of_Liverpool_logo_2007.png"))); // NOI18N
        menuLogo.setPreferredSize(new java.awt.Dimension(330, 85));
        menuLogo.setRequestFocusEnabled(false);

        menuTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        menuTitle.setText("<html><center>COMP 390: <br> Animating Algorithms</center></html>");

        org.jdesktop.layout.GroupLayout menuPanelLayout = new org.jdesktop.layout.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuPanelLayout.createSequentialGroup()
                .add(221, 221, 221)
                .add(menuLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
            .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(menuPanelLayout.createSequentialGroup()
                    .add(149, 149, 149)
                    .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                        .add(creditsLabel)
                        .add(menuPanelLayout.createSequentialGroup()
                            .add(lcsMenuButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(matrixMenuButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(knapsackMenuButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(menuTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(150, 150, 150)))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuPanelLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(menuLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
            .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(menuPanelLayout.createSequentialGroup()
                    .add(124, 124, 124)
                    .add(menuTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(64, 64, 64)
                    .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, matrixMenuButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, lcsMenuButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, knapsackMenuButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(creditsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(22, 22, 22)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(menuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(menuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lcsMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcsMenuButtonActionPerformed
        // TODO add your handling code here:
        
        this.remove(menuPanel);
        this.setTitle("Lowest Common Subsequence Algorithm");
        
        LCS lcs = new LCS();
        lcs.menu = menuPanel;
        lcs.setSize(800, 600);        
        this.setContentPane(lcs);
        this.repaint();
    }//GEN-LAST:event_lcsMenuButtonActionPerformed

    private void knapsackMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knapsackMenuButtonActionPerformed
        // TODO add your handling code here:
        this.remove(menuPanel);
        this.resize(1024,768);
        this.setLocationRelativeTo(null);
        this.setTitle("Knapsack (0,1) Algorithm");
        
        Knapsack knapsack = new Knapsack();
        knapsack.setSize(1024, 768);        
        this.setContentPane(knapsack);
        this.repaint();
    }//GEN-LAST:event_knapsackMenuButtonActionPerformed

    private void matrixMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixMenuButtonActionPerformed
        // TODO add your handling code here:
        this.remove(menuPanel);
        this.setTitle("Matrix Chain Multiplication Algorithm");
        
        MatrixChain matrix = new MatrixChain();
        matrix.setSize(800, 600);        
        this.setContentPane(matrix);
        this.repaint();
    }//GEN-LAST:event_matrixMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Native look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton knapsackMenuButton;
    private javax.swing.JButton lcsMenuButton;
    private javax.swing.JButton matrixMenuButton;
    private javax.swing.JLabel menuLogo;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel menuTitle;
    // End of variables declaration//GEN-END:variables
}
